### ISSUE TITLE
README issue?  URL is http://localhost:9000 on my machine and not http://localhost:9090 building with  `npm run serve`

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-map-public-frontend#12]
For me the project was launched at http://localhost:9000 and not at http://localhost:9090 building the project locally. Is this is an issue in the README or is this environment dependent?

**Comment by Ein-Tim** [comment]
@dreske 

I'd like to provide a PR for this issue. Could you try running the project on your environment and let me know what URL you get? :D

**Comment by MikeMcC399** [comment]
@Ein-Tim

`npm serve` uses `webpack`
https://github.com/corona-warn-app/cwa-map-public-frontend/blob/02ab69101816e8ccfdf1425a53b0c68b81900f49/package.json#L9

https://github.com/corona-warn-app/cwa-map-public-frontend/blob/02ab69101816e8ccfdf1425a53b0c68b81900f49/webpack.config.js#L48

defines port `9000`

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Ok, so the README is wrong. I will create a PR on the week end.

**Comment by Ein-Tim** [comment]
I've not forgotten this issue and a PR will follow...

**Comment by Ein-Tim** [comment]
PR #15 provided.
