### ISSUE TITLE
Server not reachable when not explicitly stating "https" as protocol

### ISSUE THREAD

**Issue by nitelow** [corona-warn-app/cwa-map-public-frontend#13]
Some web browsers can't reach the CWA map if a user types the URL without the "https://" prefix.

Tested with:
- Firefox Desktop (Gateway Timeout - "server 80.158.54.55 in unreachable at this moment)
- Edge Desktop (ERR_CONNECTION_TIMED_OUT - probably the same as Firefox)
- Chrome Desktop seems to work
- Firefox Mobile seems to work

Steps to reproduce:
- Open Firefox Desktop (v101.0.1)
- type "map.schnelltestportal.de" in address bar and try to load it
- Connection times out

Remarks:
- if site has been loaded before, it behaves correctly and forwards to "https://map.schnelltestportal.de".
- as Firefox is my main browser, some settings may vary from other browsers on my machine

Hope this is the right place for this issue as it seems to be a configuration problem :-)

**Comment by MikeMcC399** [comment]
@nitelow 

I guess your expectation is that if a user types `map.schnelltestportal.de` (without specifying the protocol scheme) into a browser address field that the page https://map.schnelltestportal.de is opened. Is that correct?

**Comment by nitelow** [comment]
@MikeMcC399 

yes, exactly

**Comment by MikeMcC399** [comment]
Attempting to access http://map.schnelltestportal.de in Google Chrome incognito mode times out

![image](https://user-images.githubusercontent.com/66998419/173323708-5c8a5484-88c5-4920-9fd5-454a3d11cce5.png)

An nginx server-side solution to this issue would be:
1. Set up the server to forward http://map.schnelltestportal.de requests to https://map.schnelltestportal.de or
2. Set up the server to respond to Upgrade-Insecure-Requests headers

**Comment by MikeMcC399** [comment]
@nitelow 

In Firefox there is a setting "HTTPS-Only Mode". If selected then that would also work around your issue.

![image](https://user-images.githubusercontent.com/66998419/173324668-5c385449-ac7c-4aff-ae92-66fc99455405.png)

**Comment by nitelow** [comment]
@MikeMcC399 thanks for your investigation and workaround proposal!

For me personally it's not a big deal. But I guess it is common practice among popular websites to forward to HTTPS automatically and therefore peoply may be put off by the site simply not loading.

**Comment by MikeMcC399** [comment]
@nitelow 

> For me personally it's not a big deal. But I guess it is common practice among popular websites to forward to HTTPS automatically and therefore peoply may be put off by the site simply not loading.

I would expect most people to arrive at the site by clicking / tapping on an existing  link, such as in the FAQ article https://www.coronawarn.app/en/faq/results/#where_can_i_get_tested. The link in this article contains the `https` protocol scheme to https://map.schnelltestportal.de/ so there would be no problem accessing the site if the link, or a bookmarked copy of it, were to be used.

The next steps have to be taken by the site owners to decide if they will make any changes to the website configuration on `map.schnelltestportal.de`.

**Comment by nitelow** [comment]
@MikeMcC399
that's a good point and maybe the reason why no one noticed this behaviour of the site before.
I also opened the map on my phone at first (through CWA), but then switched to the PC where it is easier to navigate the map on a large screen. Therefore I already knew the address but had no link to click on.

**Comment by MikeMcC399** [comment]
@nitelow 

> I also opened the map on my phone at first (through CWA), but then switched to the PC where it is easier to navigate the map on a large screen. Therefore I already knew the address but had no link to click on.

Thank you for explaining how you arrived at the problem!

For the future, maybe you would like to bookmark the following on your PC:

- https://www.coronawarn.app/en/ or https://www.coronawarn.app/de/
- in addition to https://map.schnelltestportal.de/ 

so you don't have to enter these URLs by hand.

If you are using Google as search engine I noticed that entering "schnelltestportal" brings up https://map.schnelltestportal.de/ at the top of the search list.

**Comment by nitelow** [comment]
@MikeMcC399 

Is this still being discussed? Personally I'm totally fine with it. But no popular website has the same behavior, so it naturally throws people off (especially if they don't have a technical background and can't work out why this happens). As the necessary changes should be trivial (forward http->https), this would be an easy way to increase the acceptance of the whole process :-)
If not I'm going to close the issue within the next days.

**Comment by MikeMcC399** [comment]
@nitelow 

> Is this still being discussed? 

So far the only discussion that has taken place has been between you and me, and we are both community members. 🙂 

I don't know if T-Systems (the site owner) has looked at the issue at all. Perhaps @dreske could respond here?

**Comment by dreske** [comment]
Sorry for the late response. Totally under load :D
Will fix it within the next days.

**Comment by dreske** [comment]
If you go to http, you should automatically be redirected to https

**Comment by MikeMcC399** [comment]
@dreske 

> Will fix it within the next days.

Please let us know when you have made the change so we can check it out.

**Comment by MikeMcC399** [comment]
@dreske 

Is this still on your to-do list? It sounded like you wanted to fix it very soon.

**Comment by dreske** [comment]
Hi,

yes, there were much clarification in the background what the root cause is, why it is not working. After figuring it out (load balancer setting), we got informed, that this is forbidden by security. Sorry, not the outcome I hoped for.

**Comment by Ein-Tim** [comment]
@dreske 

I just encountered this issue. Is there really no way to fix that?

**Comment by MikeMcC399** [comment]
> After figuring it out (load balancer setting), we got informed, that this is forbidden by security. 

If this is a TSI policy then it is strange that http://t-systems.com successfully redirects to https://t-systems.com in Google Chrome incognito mode.

What is different about redirecting http://map.schnelltestportal.de/ to https://map.schnelltestportal.de/?
