### ISSUE TITLE
Prepare for the end of free of charge "Bürgertests"

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-map-public-frontend#16]
If the current TestV is not replaced in time or is replaced with a TestV which does not grant free of charge tests to all citizens, it is highly likely that many testing sites will close.
Already now there are quite a few testing sites on the map which either moved or are permanently closed, but their information was not updated.
If it comes to the situation and there are no free of charge "Bürgertests" anymore, the map should be updated by the team to make sure that it stays up to date and useful for the user. 
If that's not planned, at least a hint or warning message should be shown on the website.

**Comment by Ein-Tim** [comment]
@dsarkar please mirror this to JIRA - if it makes sense to mirror it to SAP JIRA. If not @dreske, could you please raise this topic?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

According to https://github.com/corona-warn-app/cwa-quicktest-onboarding/wiki/CWA-Schnelltest-Suche maintenance of the data about individual test centers which appears on  https://map.schnelltestportal.de/ is the responsibility of each test center.

"Self-Service Portal
Das Self-Service Portal ermöglicht es Testanbietern, ihre Teststationen zu in der CWA-Schnellteststellensuche zu veröffentlichen und deren Daten zu pflegen."

"Registrierung
Die Pflege der Daten erfolgt durch die Partner selbst."

There is however also a button "Melden" for each test center if a user sees the case "Testcenter geschlossen" and wants to report it.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thank you for sharing this information. I am well aware that each test center is responsible for their appearance on the map. However, I know quite a few testing sites around me which either moved or were closed & they are all still on the map, wrongly.
I used the "Melden" feature on them, but nothing changed.

If the testing sites don't do their work, it has to be done by the team, as they are providing this service for the enduser.

If it's too huge of a workload for the team too manually cross check all test sites, it would also be possible to add a message to the Schnelltestportal for the testing sites that they'll only continue to be listed on the map if they cross-check their information and approve the information.

However, as there are also testing sites which use other testing management systems listed on the website, this is quite difficult to achieve for all testing sites.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> I used the "Melden" feature on them, but nothing changed.

Will you open a new issue for this problem?

**Comment by Ein-Tim** [comment]
@MikeMcC399 Yes, I will follow up later.

**Comment by MikeMcC399** [comment]
BMG announced on June 24, 2022 [Lauterbach: „Bürgertests werden aussagekräftiger und zielgenauer“](https://www.bundesgesundheitsministerium.de/coronavirus.html#c23063).

**Comment by Ein-Tim** [comment]
@dreske stated in https://github.com/corona-warn-app/cwa-map-public-frontend/issues/17#issuecomment-1169928203 that they are not allowed to edit anything.

I therefore suggest to implement some sort of "confirmation" feature, where the testing stations have to confirm that they 
a) still exist
b) the information on the map is correct

After a grace period (e.g. 2 months) they are removed from the map, if they do no respond.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I think your suggestion about validating data in the portal should be separate enhancement request, because it is not necessarily linked to the change of the TestV.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Maybe you misunderstood, but this OP was always about ensuring the correctness of the data listed on the map. I also provided a reasoning why this should be done with the changed TestV.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I don't think that I misunderstood. The title _Prepare for the end of free of charge "Bürgertests"_ makes it sound like the problem is only caused by TestV, but you already noticed problems yourself even before the change.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

You're right. I'll close this issue and open a more general one reg. quality assurance for the entries on the map.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

> I'll close this issue and open a more general one reg. quality assurance for the entries on the map.

I looked up some other entries and found data quality issues. There used to be a testing container near me which has now been removed. 
- There are duplicate active entries for this test station
- Both entries should be removed
- One of the entries had an incorrect PLZ

In a random search I also found other active entries where the website link said that the stations had been temporarily closed or the weblink did not work correctly.

It's really impossible to accurately judge the data quality of the test station data on https://map.schnelltestportal.de/ , however just based on what I have seen so far on a small sample of data I would not have a high confidence in the accuracy.

This is an organizational issue.

**Comment by Ein-Tim** [comment]
Closing this issue now. I really think that the maps becomes more useless with every day, if there is no quality assurance. I'll think about how we could proceed here.

**Comment by dsarkar** [comment]
@MikeMcC399 @Ein-Tim FYI we created Internal Tracking ID: [EXPOSUREAPP-13535](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13535) Maintenance https://map.schnelltestportal.de

and will forward this to the corresponding entities. Thanks.
