### ISSUE TITLE
Reporting a testing station as closed doesn't have any effect

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-map-public-frontend#17]
I reported a closed testing station as closed using the "Fehler melden" feature of the website. After 2 weeks, the testing station is still listed and nothing changed.
How exactly does this feature work?

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Which test center did you report as being closed?

The details are posted to the end-point `/api/centers/${_selectedCenter.uuid}/report` but I guess your question was more about the organizational side of how the feature works.

**Comment by dreske** [comment]
The Reports are forwarded to the operators of the test centers. We are not allowed to remove or edit testcenters ourself. 
Which testcenter did you report?

**Comment by Ein-Tim** [comment]
@dreske I reported this testing station: 

![Bildschirmfoto 2022-06-29 um 15 03 44](https://user-images.githubusercontent.com/67682506/176443018-c42052d4-ab1f-4422-9b79-09e6dc3c36d9.png)
 
 As you can see on the website of the testing station, they are not on the Theresienwiese anymore: https://www.corona-testung.de

**Comment by MikeMcC399** [comment]
@Ein-Tim 

I suspect that "Kommunales Testzentrum Theresienwiese, Matthias-Pschorr-Straße 4, 80336 München" deliberately left their entry so they could be found via https://www.corona-testung.de/ at their new address "Corona-Testzentrum München" Rosenheimer Straße 5, 81667 München.

The entry in https://map.schnelltestportal.de/ at the address Rosenheimer Straße 5, 81667 München is called "Covidzentrum Gasteig Muenchen" however that seems to be run by a different company according to https://covidzentrum.de/en/corona-test-gasteig-munich/ and in turn, that website only shows testing locations at Munich Schwabing and Munich Westend. "Covidzentrum Gasteig Muenchen" does not have a website link on https://map.schnelltestportal.de/ so I cannot be certain about the relationship to the website I looked at.

So I'm afraid the data quality in this example on https://map.schnelltestportal.de/ is less than perfect. 🙁

**Comment by Ein-Tim** [comment]
@MikeMcC399 

To me it seems like there are now two testing stations at the Gasteig 
- The one with the website https://www.corona-testung.de/
- The one with the website https://covidzentrum.de/en/corona-test-gasteig-munich/

But I'm also not too certain about that. 

I do not know if the "Kommunales Testzentrum Theresienwiese, Matthias-Pschorr-Straße 4, 80336 München" intended to leave their old address only so that users can still find it.

> So I'm afraid the data quality in this example on [map.schnelltestportal.de](https://map.schnelltestportal.de/) is less than perfect. 🙁

It's really a pity that there seems to be no Quality Assurance process in place here.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

https://map.schnelltestportal.de/ unfortunately leaves us guessing about the test centers in Munch Theresienwiese and Gasteig which have been discussed here.

https://www.gasteig.de/neuigkeiten-staedtisches-corona-testzentrum-fuer-alle-im-gasteig-in-haidhausen.html,k1,n503 announces the Gasteig test center of https://www.corona-testung.de/.

Also there is a comprehensive map https://www.testen-muenchen.de/ which covers Munich only.

**Comment by Ein-Tim** [comment]
> Also there is a comprehensive map [testen-muenchen.de](https://www.testen-muenchen.de/) which covers Munich only.

Thank you! This map only lists the "kommunales Testzentrum"... 

To find out the truth, I'd probably have to visit the Gasteig (-;

**Comment by MikeMcC399** [comment]
@Ein-Tim

For Theresienwiese

https://map.schnelltestportal.de/api/centers?latne=48.13389797586491&lngne=11.549564897376875&latsw=48.130972893573464&lngsw=11.544919311363081 continues to show 

```
{
    "centers": [
        {
            "uuid": "1fe044c3-9589-11ec-aa81-0a580a81360c",
            "name": "Kommunales Testzentrum Theresienwiese",
            "email": "info@aicher-ambulanz.de",
            "website": "https://www.corona-testung.de",
            "coordinates": {
                "longitude": 11.547204,
                "latitude": 48.1320929
            },
            "logo": "/api/operators/5a3eaabc-8da5-11ec-a6ca-0a580a813609/logo",
            "marker": null,
            "address": "Matthias-Pschorr-Straße 4, 80336 München",
            "openingHours": [],
            "addressNote": "Theresienwiese",
            "appointment": "Required",
            "testKinds": [
                "Antigen",
                "PCR"
            ],
            "dcc": false
        }
    ]
}

```

The linked website https://www.corona-testung.de/ says "Achtung! Ab dem 22.04.2022 finden die Testungen im Gasteig in der Rosenheimer Straße 5 statt. Bitte beachten Sie, dass dort kein Drive-In möglich ist."

I don't think that it should be a community responsibility to ensure that the data on https://map.schnelltestportal.de/ is correct. This is really a governance issue. It seems also that there is no follow-up after the community reports an issue.

---

I also reported about the Gasteig issues through the "Melden" button several days ago. Nothing has changed on https://map.schnelltestportal.de though.

https://map.schnelltestportal.de/api/centers?latne=48.13398028837461&lngne=11.59442927099013&latsw=48.12812996654555&lngsw=11.585138098962542
stills shows the duplicates and the misspelled location. According to the website https://covidzentrum.de/corona-test-gasteig-muenchen/ the company is no longer located at Gasteig.

```
{
    "centers": [
        {
            "uuid": "545dfa3d-6e3d-11ec-bd8b-0a580a823421",
            "name": "Covidzentrum Gassteig",
            "email": null,
            "website": "https://covidzentrum.de/corona-test-gasteig-muenchen/",
            "coordinates": {
                "longitude": 11.5914022,
                "latitude": 48.131652
            },
            "logo": null,
            "marker": null,
            "address": "Rosenheimer Straße 5, 81667 München",
            "openingHours": [
                "Mo. - So.:   07:00 - 20:00 Uhr"
            ],
            "addressNote": null,
            "appointment": "Possible",
            "testKinds": [
                "Antigen",
                "PCR"
            ],
            "dcc": true
        },
        {
            "uuid": "7d502f0f-534c-11ec-8121-0a580a82340b",
            "name": "Covidzentrum Gasteig Muenchen",
            "email": "gasteig@covidzentrum.de",
            "website": null,
            "coordinates": {
                "longitude": 11.5914022,
                "latitude": 48.131652
            },
            "logo": null,
            "marker": null,
            "address": "Rosenheimer Strasse 5, 81667 Muenchen",
            "openingHours": [],
            "addressNote": "ja",
            "appointment": null,
            "testKinds": [
                "PCR"
            ],
            "dcc": false
        }
    ]
}

```

---

This does seem to be a generic issue:

- Sites are not responding to reports
- Closed sites are not removing their entries

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thank you for the comment! I agree with you, this is nothing that should be done by the community.

@dreske If a user reports an error, how is this presented to the testing station? Do they get a mail, or how are they made aware of the issue?

**Comment by MikeMcC399** [comment]
> @Ein-Tim 
> 
> To me it seems like there are now two testing stations at the Gasteig
> 
> * The one with the website https://www.corona-testung.de/
> * The one with the website https://covidzentrum.de/en/corona-test-gasteig-munich/

Neither of the websites above have current entries for Gasteig, München. Instead I found https://www.vitotest.de/gasteig for Testzentrum München Gasteig, Rosenheimer Straße 5, 81667 München, but only by using the website https://www.testen-muenchen.de/ instead of https://map.schnelltestportal.de/.

In any case the current entry in https://map.schnelltestportal.de/ for Rosenheimer Straße 5, 81667 München is wrong. It shows "Covidzentrum Gassteig" with misspelled "Gasteig", a link to https://covidzentrum.de/corona-test-gasteig-muenchen/ and this link has no entry for the corresponding address.

So for the address Rosenheimer Straße 5, 81667 München, which is now the main vaccination center for Munich ([Impfzentrum München](https://www.muenchen.de/aktuell/2021/corona-impfung-impftermin-impfzentrum-muenchen.html)) the details of the co-located test center are completely wrong in https://map.schnelltestportal.de/ and haven't been fixed since you reported the issue both through the "Melden" function and here.

**Comment by Ein-Tim** [comment]
With the latest changes I consider this as sufficiently addressed.
