### ISSUE TITLE
Symbols may show on top of each other

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-map-public-frontend#18]
## Bug

I wanted to check a situation where it seems like there are two testing stations registered at the same address. However, this leads to the situation which can be seen on the screenshot below. It is no possible to click on the EU icon, as always the other testing station is selected. 

![Bildschirmfoto 2022-06-29 um 15 34 52](https://user-images.githubusercontent.com/67682506/176449589-f117f739-4f44-4c9c-8932-878030dd8838.png)

## Suggested fix

If there are two entries for the same address, show the symbols next to each other, not on top of each other.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

If you use the filter Digital Covid Certificate in the search then you can select one center only.

**Comment by MikeMcC399** [comment]
On https://map.schnelltestportal.de/ under the address Rosenheimer Str. 5, 81667 München there are two centers registered, which appear to be from the same company. The companies have similar but different names. 

---
The one with a website link https://covidzentrum.de/corona-test-gasteig-muenchen/ has the name of the location spelled incorrectly: it should be Gasteig not Gassteig. The website shows that this company is not located at Gasteig, only at Schwabing and Westend.

![Gassteig](https://user-images.githubusercontent.com/66998419/176460873-7d5c7f80-7dfa-459e-9852-a0b53676f198.jpg)

---
The other test station has no website link and seems to be a subset of the other test station at the same address.

![Gasteig](https://user-images.githubusercontent.com/66998419/176460905-fe44f276-4946-4b97-8316-815958c96ce0.jpg)

---

This is a data quality issue.

Edit: I reported these issues via the "Melden" option in the UI of https://map.schnelltestportal.de/ 

---

Raw data follows:

https://map.schnelltestportal.de/api/centers?latne=48.132&lngne=11.592&latsw=48.130&lngsw=11.590

```
{

    "centers": [
        {
            "uuid": "545dfa3d-6e3d-11ec-bd8b-0a580a823421",
            "name": "Covidzentrum Gassteig",
            "email": null,
            "website": "https://covidzentrum.de/corona-test-gasteig-muenchen/",
            "coordinates": {
                "longitude": 11.5914022,
                "latitude": 48.131652
            },
            "logo": null,
            "marker": null,
            "address": "Rosenheimer Straße 5, 81667 München",
            "openingHours": [
                "Mo. - So.:   07:00 - 20:00 Uhr"
            ],
            "addressNote": null,
            "appointment": "Possible",
            "testKinds": [
                "Antigen",
                "PCR"
            ],
            "dcc": true
        },
        {
            "uuid": "7d502f0f-534c-11ec-8121-0a580a82340b",
            "name": "Covidzentrum Gasteig Muenchen",
            "email": "gasteig@covidzentrum.de",
            "website": null,
            "coordinates": {
                "longitude": 11.5914022,
                "latitude": 48.131652
            },
            "logo": null,
            "marker": null,
            "address": "Rosenheimer Strasse 5, 81667 Muenchen",
            "openingHours": [],
            "addressNote": "ja",
            "appointment": null,
            "testKinds": [
                "PCR"
            ],
            "dcc": false
        }
    ]
}
```

**Comment by Ein-Tim** [comment]
@MikeMcC399 

Thank you so much for continuing the investigation! 

Do you agree with me that it is not good UI / a bug that it is possible that the symbols are stacked over each other?

**Comment by MikeMcC399** [comment]
> @Ein-Tim 
> 
> Do you agree with me that it is not good UI / a bug that it is possible that the symbols are stacked over each other?

If there is more than one entry at one address then it should be possible to access each of them. So, yes this is a UI issue. 

In addition some of these double entries are data quality issues where the same entity has two entries, where I would expect there to be only one.

It is however feasible that multiple test stations share the same address, for instance a medical center with specialist doctors who each have their own practice but share the postal address. I think this is probably the exception though.

**Comment by MikeMcC399** [comment]
- I added an enhancement request https://github.com/corona-warn-app/cwa-map-backend/issues/3 to the backend to check for duplicate entries.

**Comment by dreske** [comment]
Partners can specifiy their exact marker position now.
But sometimes the cause is simply, that two partners provides the same test center.
