### ISSUE TITLE
Quality of test station data on https://map.schnelltestportal.de/

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-map-public-frontend#19]
## Where to find the issue

https://map.schnelltestportal.de/

## Describe the issue

The quality of data on the official Federal German website https://map.schnelltestportal.de/ listing available testing stations is questionable.

Just in a small sample of test stations, the following issues have been observed:
- test station closed, entry still available
- test station moved, old entry still available, new entry not available
- multiple entries for one test station with different spellings and different information
- link to website does not work (404 error)
- link to website shows test station has moved or closed

(See other issues raised in https://github.com/corona-warn-app/cwa-map-public-frontend/issues and https://github.com/corona-warn-app/cwa-map-backend.)

For those issues which were reported via the "Melden" link of https://map.schnelltestportal.de/ and waiting for one week no changes were visible on the website.

Considering that test stations are legally controlled and checks are legally mandated, it seems strange that the data on https://map.schnelltestportal.de/ is not in a better condition.

See [Fragen und Antworten zu COVID-19 Tests](https://www.bundesgesundheitsministerium.de/coronavirus/nationale-teststrategie/faq-covid-19-tests.html) including:

- [Wer ist zuständig für die Beauftragung von Leistungserbringern? Unter welchen Voraussetzungen erfolgt eine Beauftragung und wie werden die Kriterien überprüft?](https://www.bundesgesundheitsministerium.de/coronavirus/nationale-teststrategie/faq-covid-19-tests.html#c23834)

## Suggestion

This is not an issue that can be resolved through GitHub. It can only be raised here for the attention of responsible authorities e.g. the public health authorities (ÖGD) and the Kassenärztlichen Vereinigungen to improve the governance of the official test station data published on https://map.schnelltestportal.de/.

**Comment by dreske** [comment]
We are currently working hard on this issue. Data quality should be improved within the next weeks.

**Comment by MikeMcC399** [comment]
@dreske 

> We are currently working hard on this issue. Data quality should be improved within the next weeks.

That is good news! I can imagine that this is a lot of work, so good luck in making progress!

**Comment by dsarkar** [comment]
Monitored in Internal Tracking ID: [EXPOSUREAPP-13535](https://jira-ibs.wbs.net.sap/browse/EXPOSUREAPP-13535)

**Comment by MikeMcC399** [comment]
@dreske 

> We are currently working hard on this issue. Data quality should be improved within the next weeks.

Do you have any progress to report?

Some of the example testing stations which were mentioned in other issues are still incorrect. There were several cases where testing stations seemed to have been moved or are no longer available. The portal information is contradictory to the linked website information of the testing provider.

Just for one example from https://github.com/corona-warn-app/cwa-map-public-frontend/issues/17#issuecomment-1169955216. https://map.schnelltestportal.de/ says there is a test station "Kommunales Testzentrum Theresienwiese" however the linked website https://www.corona-testung.de/ does not list this location at all.

![image](https://user-images.githubusercontent.com/66998419/185443673-59284f74-7458-4000-9857-562ebfde5cc2.png)

**Comment by dreske** [comment]
Yes, there will BE a change next week, where are more transparent to the
user about the age of an entry and if the operator es updating its data
regularly. Also there will be more pressure on the providers to keep their
data up to Date, to prevent us to show warnings about the providers to the
user.

WE are prohibited to hide centers based on user reports. One Extension
could be an info like "5 users marked this Center as closed". Will propose
it tomorrow.

Mike McCready ***@***.***> schrieb am Do., 18. Aug. 2022,
18:15:

**Comment by Ein-Tim** [comment]
@dreske Looking at the map today, I can't see when the data has been last updated or if it is updated regularly, so I assume this change didn't went live yet?

**Comment by MikeMcC399** [comment]
For the issues which were already reported, I cannot see any improvement in the data:

Issue type | Issue | Center Name | Address
--- | --- | --- | ---
Multiple entries for one test station with different spellings and different information | - https://github.com/corona-warn-app/cwa-map-backend/issues/3 | 1. München - am Klinikum rechts der Isar<br>2. Testzentrum Rechts d. Isar Test Smart GmbH<br>3. test smart - Testzentrum am Klinikum rechts der Isar | Trogerstraße 27, 81675 München
Link to website does not work (404 error) | - https://github.com/corona-warn-app/cwa-map-backend/issues/4 | Isartor - München | Thomas-Wimmer-Ring 1/3, 80539 München
Link to website shows test station has moved or closed | - https://github.com/corona-warn-app/cwa-map-public-frontend/issues/17 | Kommunales Testzentrum Theresienwiese | Matthias-Pschorr-Straße 4, 80336 München

**Comment by Ein-Tim** [comment]
@MikeMcC399

The changes have been deployed now. What do you think, is this change sufficient? 
![Bildschirmfoto 2022-09-09 um 12 28 29](https://user-images.githubusercontent.com/67682506/189330220-4741afad-1f77-48f4-a56c-0f5cafa3d23f.png)

**Comment by MikeMcC399** [comment]
@dreske 

I checked the three test stations listed in https://github.com/corona-warn-app/cwa-map-public-frontend/issues/19#issuecomment-1236310015 and they all show warnings. I'm seeing two possible warnings:

- Die Teststelle wurde das letzte Mal vor über n Wochen aktualisiert. Bitte beachten Sie, dass die Daten nicht mehr korrekt sein könnten.
- Aktuell erhalten wir keine Rückmeldung über die Aktualität der Daten vom Betreiber.

![image](https://user-images.githubusercontent.com/66998419/189331702-1ad2983c-7248-4702-b1a4-ae82f5be7b5c.png)

Although this does not solve this issue of stale data, it at least gives users a warning and I think this is a good enhancement.

I will close this issue now, as I don't think that much more can be achieved through GitHub. Improving the data quality will need to be an ongoing background process.
