### ISSUE TITLE
Link to website in repository here

### ISSUE THREAD

**Issue by rugk** [corona-warn-app/cwa-map-public-frontend#2]
IMHO the best would be to just click on the wheel in the “About” section of your repository and add the following website link:
https://map.schnelltestportal.de/
![grafik](https://user-images.githubusercontent.com/11966684/146845648-fc51bfd4-400f-43d8-a61b-12fd45062635.png)

**Comment by daniel-eder** [comment]
Done - thank you for the suggestion!
