### ISSUE TITLE
Remove text "Die hier gezeigten Schnelltestzentren werden täglich aktualisiert"

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-map-public-frontend#20]
## Current Implementation
Currently on https://map.schnelltestportal.de on the top it says: "Die hier gezeigten Schnelltestzentren werden täglich aktualisiert".

## Suggested Enhancement
I would suggest to remove this text or replace it with another text, as there are quite some data quality issues (see https://github.com/corona-warn-app/cwa-map-public-frontend/issues/19).

## Expected Benefits
The text "Die hier gezeigten Schnelltestzentren werden täglich aktualisiert" may be misleading to the user as they expect that there are no closed stations listed, etc.. 

## Additional information
I will provide a PR removing the text.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

- Instead of a text implying that the data is very up-to-date, it would be more helpful to display a warning that the data may be inaccurate. Perhaps the text "Für die Richtigkeit der Teststellendaten sind die Testanbieter verantwortlich." from https://map.schnelltestportal.de/usage.html needs to be displayed more prominently? 

- According to https://map.schnelltestportal.de/impressum.html "T-Systems International GmbH" is responsible for the site. The changes proposed in https://github.com/corona-warn-app/cwa-map-public-frontend/issues/19#issuecomment-1219896481 do not seem to have taken effect so far.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> Instead of a text implying that the data is very up-to-date, it would be more helpful to display a warning that the data may be inaccurate. Perhaps the text "Für die Richtigkeit der Teststellendaten sind die Testanbieter verantwortlich." from [map.schnelltestportal.de/usage.html](https://map.schnelltestportal.de/usage.html) needs to be displayed more prominently?

This seems like a very good idea! I will provide a PR replacing the text "Die hier gezeigten Schnelltestzentren werden täglich aktualisiert" with the text "Für die Richtigkeit der Teststellendaten sind die Testanbieter verantwortlich" tomorrow.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

See changes in https://github.com/corona-warn-app/cwa-map-public-frontend/commit/eb93838c0c85f943e5508e3b78cf44fce227c817

**Comment by Ein-Tim** [comment]
@MikeMcC399 The commit you mentioned does not changed the text "Die hier gezeigten Schnelltestzentren werden täglich aktualisiert" if I'm not mistaken.

**Comment by Ein-Tim** [comment]
- PR #21 provided.

**Comment by MikeMcC399** [comment]
@Ein-Tim 

Sorry for the uncommented reference to the new commit https://github.com/corona-warn-app/cwa-map-public-frontend/commit/eb93838c0c85f943e5508e3b78cf44fce227c817. What I meant was that you might like to wait until this change has gone into production so you can look at the effect and judge if changing the text as proposed is necessary.

It seems that there will be a warning if the data for a specific test station has not been updated for some time. This would be implementing the description from https://github.com/corona-warn-app/cwa-map-public-frontend/issues/19#issuecomment-1219896481 that @dreske wrote about.

**Comment by Ein-Tim** [comment]
@MikeMcC399 

> What I meant was that you might like to wait until this change has gone into production so you can look at the effect and judge if changing the text as proposed is necessary.

Ah, now I understand! The new change definitely looks good and will improve the situation drastically, but still I think the statement that testing stations are updated daily should be replaced or removed.

I'll leave my PR open and wait for feedback from @dreske.
