### ISSUE TITLE
Testing web frontend gives proxy error

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-map-public-frontend#22]
## Where to find the issue

Instructions in [README.md](https://github.com/corona-warn-app/cwa-map-public-frontend/blob/main/README.md)

## Describe the issue

Following the instructions in [README.md](https://github.com/corona-warn-app/cwa-map-public-frontend/blob/main/README.md) to run the web front end locally leads to a proxy error. The map is shown, however no testing stations are shown on the map.

## Steps to reproduce

```
npm install
npm run serve
```
In Google Chrome access http://localhost:9000
Type "Berlin" in search field of map front end
Note error in terminal window `http://localhost:9090/ [ECONNREFUSED]`:

```
<e> [webpack-dev-server] [HPM] Error occurred while proxying request localhost:9000/api/centers/bounds?address=Berlin to http://localhost:9090/ [ECONNREFUSED] (https://nodejs.org/api/errors.html#errors_common_system_errors)
```

**Comment by dreske** [comment]
In proxy.conf.json the Backend needs to be configured. You could also
configure the production url.

Mike McCready ***@***.***> schrieb am Mo., 5. Sept. 2022,
13:55:

**Comment by MikeMcC399** [comment]
@dreske 

> In proxy.conf.json the Backend needs to be configured. You could also
configure the production url.

Could you give exact instructions for this? I could not find any file with the name `proxy.conf.json`. What are the steps to use the production database of test stations?
