### ISSUE TITLE
Address format errors in T-Systems International GmbH Impressum

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-map-public-frontend#23]
## Where to find the issue

https://map.schnelltestportal.de/impressum.html

## Describe the issues

1. Addresses in Frankfurt and Bonn use the format "D-". This was deprecated in September 1999. See https://www.deutschepost.de/de/b/briefe-ins-ausland/laenderkuerzel-laendercode.html:<br><br>"**Was ist aus den Ländercodes geworden?**<br>
Die Angabe der Länderkürzel vor der Postleitzahl bei der Adressangabe auf Briefen und Paketen wurde offiziell am 1. September 1999 abgeschafft."

2. There is a hyphen between the street name and house number in "Friedrich-Ebert-Allee-140". There should be no hyphen there.

## Suggestion

Change to

```
Hahnstraße 43d
60528 Frankfurt am Main, Germany
```

and

```
Friedrich-Ebert-Allee 140
53113 Bonn, Germany
```

## Comment

https://www.t-systems.com/de/en/imprint and
https://www.t-systems.com/de/de/impressum

also contain these formatting errors.

For comparison, refer also to https://www.telekom.com/en/deutsche-telekom/imprint-1742 from Deutsche Telekom AG which formats the addresses correctly i.e. no use of "D-" and no hyphen in the address in front of the house number "Friedrich-Ebert-Allee 140".

## References

- https://www.upu.int/UPU/media/upu/PostalEntitiesFiles/addressingUnit/deuEn.pdf "In items for Germany, on no account should a country code (D- or DE-) be written in front of the postcode. This could cause delays in processing items with sorting machine"
- https://www.deutschepost.de/de/b/briefe-ins-ausland/brief-beschriften.html "Bei Sendungen ins Ausland werden keine [Länderkürzel](http://www.deutschepost.de/de/b/briefe-ins-ausland/laenderkuerzel-laendercode.html) (z.B. F, NL) vor Ortsnamen bzw. Postleitzahl gesetzt!"

**Comment by dreske** [comment]
Thank you. I will change it.

Mike McCready ***@***.***> schrieb am Mo., 5. Sept. 2022,
14:51:

**Comment by MikeMcC399** [comment]
@dreske 

>  I will change it.

Thank you. I also sent mail to info@t-systems.com suggesting that they correct the main T-Systems Impressum page.

**Comment by MikeMcC399** [comment]
@dreske 

- I submitted PR https://github.com/corona-warn-app/cwa-map-public-frontend/pull/25 to resolve the issue, in case you would like to use this.

**Comment by MikeMcC399** [comment]
@dreske 

Thank you for merging! When will you push this (and other changes) to production?

**Comment by dreske** [comment]
Plan was today, but due some ops issued, we've moved to tomorrow.

Mike McCready ***@***.***> schrieb am Do., 8. Sept. 2022,
10:41:

**Comment by MikeMcC399** [comment]
Closing, since the source is fixed and just waiting for move to production.
