### ISSUE TITLE
Extend filter options to only show recently updated testing stations

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-map-public-frontend#27]
## Feature description

The CWA "Schnellteststellensuche" map should be extended with a new filter option, which allows the user to filter out testing stations which did not update their data in the last x weeks.

## Problem and motivation
Currently, there are a lot of testing stations on the map which either closed or moved to a new location. 
While first steps have been taken mitigate this problem & users are informed if data may be out of data, the map itself, where the user has to search for testing stations, still lists all entries, no matter when the data was last updated.

Giving the user a filter option which filters out stations which did not update their information for a long period of time, gives the user the possibility to only view relevant entries on the map.

## Outstanding questions

- Should this filter be set to ON or OFF by default?
- What period of time do we take here? The last 4 weeks? Or rather the last 12 weeks?

**Comment by dreske** [comment]
Sounds like a very good Idea. Will discuss it this week.

Tim ***@***.***> schrieb am Sa., 10. Sept. 2022, 00:42:

**Comment by Ein-Tim** [comment]
Kudos to the Twitter user who came up with this idea: https://twitter.com/joergmkam/status/1568314425194446850?s=20&t=sTTtSs-hSmZA7wdLdOGfWw

**Comment by Ein-Tim** [comment]
@dreske What was the result of the discussion? Will this be implemented?

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect this issue to be addressed anymore. I'm therefore closing this issue.
