### ISSUE TITLE
No new release on GitHub for data quality fixes?

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-map-public-frontend#28]
The last version that was released here on GitHub is version 1.3.2. I think releasing a new version which includes all the changes which were done to improve data quality would be a good idea.

**Comment by Ein-Tim** [comment]
Ok, seems like that's not planned.

**Comment by dreske** [comment]
Will create the Release these days :D

Tim ***@***.***> schrieb am Mi., 28. Sept. 2022, 15:16:
