### ISSUE TITLE
Status due to TestV changes on March 1, 2023

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-map-public-frontend#35]
https://www.buzer.de/gesetz/14991/v292062-2023-03-01.htm shows that the following legal paragraphs from the TestV are no longer in force:

§ 1 Anspruch
§ 2 Testungen von nachweislich infizierten Personen, Kontaktpersonen und von Personen mit Voraufenthalt in Virusvariantengebieten
§ 3 Testungen von Personen nach Auftreten von Infektionen in Einrichtungen und Unternehmen
§ 4 Testungen zur Verhütung der Verbreitung des Coronavirus SARS-CoV-2
§ 4a Bürgertestung
§ 4b Bestätigende Diagnostik-Testung
§ 5 Häufigkeit der Testungen
§ 6 Leistungserbringung

A random check of several testing sites showed in their web presence that they no longer exist or that they have a notice of shutting down on March 1, 2023. Only test facilities offered by doctors in their regular doctor's surgery / office or tests in pharmacies seem to be continuing.

Will there be any special notice on https://map.schnelltestportal.de/ to this effect?

**Comment by MikeMcC399** [comment]
This is just a selection of error messages or calendars which offer no appointments. I just clicked on a few test centers in the middle of Munich:

![image](https://user-images.githubusercontent.com/66998419/222253216-9b651205-bb91-4b4b-9cac-3d34679e7c38.png)

![image](https://user-images.githubusercontent.com/66998419/222253584-29e6bd8b-4e5c-4345-998a-2b2f515ab9c5.png)

![image](https://user-images.githubusercontent.com/66998419/222253678-44ad71d1-f671-4eb4-8b81-e7c4a436ade6.png)

![image](https://user-images.githubusercontent.com/66998419/222253975-7fdeaa1f-ff23-4865-b1d4-6e3f342716f9.png)

![image](https://user-images.githubusercontent.com/66998419/222254170-d9bc0861-de7f-4d76-9149-b0058518ef05.png)

![image](https://user-images.githubusercontent.com/66998419/222254347-a3ada485-4bcd-4d0b-8c9e-51d98600f488.png)

**Comment by MikeMcC399** [comment]
Possibly this site needs a disclaimer added to it

"Major changes to the [Coronavirus-Testverordnung - TestV](https://www.gesetze-im-internet.de/coronatestv_2021-10/), which took effect on March 1, 2023, remove special testing arrangements for COVID-19 / SARS-CoV-2 and many temporary testing stations are now closed. The data for testing stations may no longer be reliable."

**Comment by dreske** [comment]
I will clarify this. Sorry for the late response, but since the regulations
ended, the partners are "not that" reliable.... -.-

Am Do., 2. März 2023 um 12:55 Uhr schrieb Mike McCready <
***@***.***>:

**Comment by MikeMcC399** [comment]
@dreske 

> I will clarify this.

Thank you!

I understand that test partners would not be interested in cleaning up the website data if there is no longer any legal basis for them to be testing any more. The responsibility is with "T-Systems International GmbH" according to the https://map.schnelltestportal.de/impressum.html to make sure the website fits the current legal status.

**Comment by MikeMcC399** [comment]
See also https://www.zusammengegencorona.de/testen/ich-will-mich-auf-corona-testen-lassen-wo-wann-und-wie/ (German language) for an overview.

The cleanest solution would be to remove the test station data from https://map.schnelltestportal.de/ and retire the portal.

**Comment by MikeMcC399** [comment]
@dreske 

Has TSI come to a decision what to do with the website https://map.schnelltestportal.de/? With effect of March 1, 2023 It has clearly lost most of its value in identifying places to get tested. See BMG [nationale Teststrategie](https://www.bundesgesundheitsministerium.de/coronavirus/nationale-teststrategie/faq-covid-19-tests.html).

It is not required to be tested before visiting hospitals etc. There are no QR codes any more that can be used by the CWA app, so the number of tests reported to the app has dropped to zero. 

![image](https://user-images.githubusercontent.com/66998419/223348069-bb97a779-1cfd-4dd4-b565-b2646aec8049.png)

**Comment by dreske** [comment]
We are preparing shutdown. Partners get cancelled these days.

Mike McCready ***@***.***> schrieb am Di., 7. März 2023,
08:03:

**Comment by MikeMcC399** [comment]
@dreske 

> We are preparing shutdown. Partners get cancelled these days.

Many thanks for the update! Will the website https://map.schnelltestportal.de/ stay online with replaced content or will the address https://map.schnelltestportal.de/ stop responding?

**Comment by Ein-Tim** [comment]
The page will be shut down when the development of the CWA ends.

**Comment by MikeMcC399** [comment]
This issue is now fully resolved:

![image](https://user-images.githubusercontent.com/66998419/233637984-d4655c95-e968-4a6a-a98d-d0e92f665608.png)
