### ISSUE TITLE
Show whether/how accessible a testing station is

### ISSUE THREAD

**Issue by Ein-Tim** [corona-warn-app/cwa-map-public-frontend#7]
## Feature description
The testing stations should have the option to provide information on whether the testing station is accessible e.g. for people in wheelchairs. If they are accessible, it should be possible to add additional details (like the existence of an elevator, floor-level entry, etc.)

## Problem and motivation
I think the motivation is obvious here, this change would give people who need it very important information. Not only people in wheelchairs but also elderly people, etc. would profit.

## Additional information
Providing the information on whether/how accessible a testing station is should be optional for testing stations.

**Comment by dreske** [comment]
For now, it is in the responsibility of the test center operators to provide these Information using the comment field. But it would be cool, to filter for this! We will evaluate.

**Comment by Ein-Tim** [comment]
As the CWA project went into ramp-down mode, I don't expect to see this feature being implemented anymore. I'm therefore closing this issue now.
