### ISSUE TITLE
CODEOWNERS file missing

### ISSUE THREAD

**Issue by MikeMcC399** [corona-warn-app/cwa-map-public-frontend#9]
## Problem

[CONTRIBUTING.md](https://github.com/corona-warn-app/cwa-map-public-frontend/blob/main/CONTRIBUTING.md) contains a link to [CODEOWNERS](https://github.com/corona-warn-app/cwa-map-public-frontend/blob/main/CODEOWNERS), however this file does not exist. Clicking on the link gives a 404 error from GitHub.

## Expected

The repository should contain a [CODEOWNERS](https://github.com/corona-warn-app/cwa-map-public-frontend/blob/main/CODEOWNERS) file.

## Suggested resolution

Either

1. add a [CODEOWNERS](https://github.com/corona-warn-app/cwa-map-public-frontend/blob/main/CODEOWNERS) file to the repository or
2. remove the reference to it in [CONTRIBUTING.md](https://github.com/corona-warn-app/cwa-map-public-frontend/blob/main/CONTRIBUTING.md)

**Comment by MikeMcC399** [comment]
@dreske 

https://github.com/corona-warn-app/cwa-website/blob/master/CODEOWNERS is an example from another CWA repository.

Help and syntax for such a file is available on https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

I can provide you a PR to remove the reference to [CODEOWNERS](https://github.com/corona-warn-app/cwa-map-public-frontend/blob/main/CODEOWNERS) in [CONTRIBUTING.md](https://github.com/corona-warn-app/cwa-map-public-frontend/blob/main/CONTRIBUTING.md) for option 2. if that is what you want.

**Comment by dreske** [comment]
fixed

**Comment by MikeMcC399** [comment]
@dreske 

Thanks for the attempt to fix, however that throws an error:

![image](https://user-images.githubusercontent.com/66998419/164240452-dca59f67-89b3-4269-a950-9825c5312282.png)

**Comment by Ein-Tim** [comment]
@MikeMcC399 Strange, here it shows as valid: 

![Bildschirmfoto 2022-04-20 um 15 27 19](https://user-images.githubusercontent.com/67682506/164240946-40b0d6c4-f2e1-4806-a64a-57766ee98ef8.png)

**Comment by MikeMcC399** [comment]
It's OK for me too now.

**Comment by dreske** [comment]
There was a permission issue. Fixed already
